### ISSUE TITLE
expansion team championships

### ISSUE THREAD

**Issue by robbyblum** [hexane360/edensity-sim#2]
https://github.com/hexane360/edensity-sim/blob/ae4f3591b2024a25e6fa1cee8070dadde20e3efa/fetch.js#L246

Looks like you probably already know this, but expansion teams don't have credit for the championships they arrived with, which they should.

It looks like you're getting championships by iterating through the playoffs, which works for every other team, but not this. The teams have a number of championships in their object in the Blaseball API, though, which you can just grab immediately. For instance: 

https://www.blaseball.com/database/team?id=8d87c468-699a-47a8-b40d-cfb73a5660ad

`"championships": 4,`

And this should work for the expansion teams as well. Probably don't need to iterate through playoffs at all, tbh.

**Comment by hexane360** [comment]
Oh wow, that saves a lot of trouble. I didn't notice that key in my original searches. I'm already fetching the blaseball API team info, so I can do this directly

**Comment by hexane360** [comment]
Fixed in 3a849da
