### ISSUE TITLE
get player eDensity directly from the API?

### ISSUE THREAD

**Issue by robbyblum** [hexane360/edensity-sim#3]
https://github.com/hexane360/edensity-sim/blob/e18c0f29ab815c76f6f0b4e32f65c541182d0614/sim.js#L466

Player eDensity is stored in the player objects, so you don't need to calculate it yourself. Example:

https://www.blaseball.com/database/players?ids=90c2cec7-0ed5-426a-9de8-754f34d59b39

"eDensity": 28.98165784243294,

**Comment by hexane360** [comment]
Fixed in 0c476ad
