### ISSUE TITLE
Birds remove eDensity, so they should appear in this too

### ISSUE THREAD

**Issue by robbyblum** [hexane360/edensity-sim#7]
From maincord:

> hey, I don't know who made the website that visually represents eDensity (presumably someone named/associated with "hexane"), but here's a tidbit of knowledge from the fridays
> 
> our calculated eDensity is 1949.490
> our actual eDensity is 1809.490
> 
> the difference between these two values is 140, which is exactly the amount of birds the Fridays have in our stadium, so if anyone wants to factor this into the hexane eDensity sim, go ahead/please do!

**Comment by hexane360** [comment]
Thanks, I'll definitely take a look at this. I haven't been keeping up with the last couple seasons, but it's good to know we're discovering more of the composition of eDensity. I love that birds have negative eDensity. I think even pre-birds there were a few other factors that caused miscalculations, so I'll keep an eye out for those.

**Comment by hexane360** [comment]
This should be fixed now. There's still a small gap between predicted and actual, so if you find any new eDensity components I'd be happy to include them.
