### ISSUE TITLE
Properly account for Negative players

### ISSUE THREAD

**Issue by LemmaEOF** [hexane360/edensity-sim#8]
The **Negative** modification makes a player affected by it have negative eDensity instead of positive eDensity. This leads to calculation inaccuracies on Teams with Negative players, such as the Mechanics, Garages, Millennials, and every other team that won an Alternate Trust this season.

**Comment by hexane360** [comment]
I knew this day would come...

**Comment by hexane360** [comment]
On closer inspection, it looks like this is actually working correctly, at least partially.

Take the garages. Lotus Mango is correctly reported by the Blaseball API as having a negative eDensity. Also, the garage's calculated eDensity is very close to their actual eDensity (2159 vs 2153). However, Brisket Friendo is not reported as having a negative eDensity, despite having the negative modification.

**Comment by LemmaEOF** [comment]
...Huh, I'm looking around and there's a *lot* of variance both up and down. I wonder if there's more going on behind the scenes...

**Comment by hexane360** [comment]
It looks like eDensity updates at the beginning of each day. Players who received Negative this election should have a correct eDensity on day 1 next season.
